name: Trigger Landing Page Build

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Landing Page build
        run: curl --location --request POST '${{ secrets.LP_TRIGGER_DEPLOY_URL }}'
